# Generated by Django 3.2.5 on 2022-06-30 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20220619_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='room',
            name='Participants',
            field=models.ManyToManyField(blank=True, related_name='Participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
